# Generated by Django 4.2.8 on 2024-06-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestrator", "0001_init"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskworker",
            name="task_type",
        ),
        migrations.AddField(
            model_name="taskworker",
            name="task_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
