# Generated by Django 4.2.8 on 2024-06-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestrator", "0002_add_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="track_id",
            field=models.CharField(
                blank=True,
                help_text="The tracking ID of the task, will start with T-{cluster_name}-{id}",
                max_length=100,
                null=True,
            ),
        ),
    ]
