# Generated by Django 4.2.8 on 2024-06-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestrator", "0003_add_trackid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_name",
            field=models.CharField(
                choices=[
                    ("quantization_llm", "Quantization LLM"),
                    ("hf_llm", "HF LLM"),
                    ("emotion_detection", "Emotion Detection"),
                    ("speech2text", "Speech2Text"),
                    ("text2speech", "Text2Speech"),
                    ("general_ml", "General ML"),
                ],
                help_text="Select the type of task",
                max_length=100,
            ),
        ),
    ]
