# Generated by Django 4.2.8 on 2024-06-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestrator", "0004_add_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_name",
            field=models.CharField(help_text="The name of the task", max_length=100),
        ),
    ]
