# Generated by Django 4.2.8 on 2024-03-02 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMRequestRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("prompt", models.TextField()),
                ("response", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "task",
                    models.CharField(
                        choices=[
                            ("chat-completion", "Chat Completion"),
                            ("completion", "Completion"),
                            ("create-embedding", "Create Embedding"),
                        ],
                        default="completion",
                        max_length=100,
                    ),
                ),
                ("completed_in_seconds", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
