# Generated by Django 4.2.8 on 2024-06-25 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMConfigRecords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("model_size", models.CharField(max_length=100)),
                ("model_family", models.CharField(max_length=100)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("hf", "HuggingFace"),
                            ("api", "API"),
                            ("llama.cpp", "llama.cpp"),
                            ("chatglm.cpp", "chatglm.cpp"),
                        ],
                        default="hf",
                        max_length=100,
                    ),
                ),
                ("repo", models.CharField(blank=True, max_length=100, null=True)),
                ("filename", models.CharField(blank=True, max_length=100, null=True)),
                ("file_size", models.FloatField(blank=True, null=True)),
                ("available", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LLMRequestResultDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="The name of the task for tracking",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "progress",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("started", "Started"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
                (
                    "download_link",
                    models.URLField(
                        blank=True, help_text="The download link in s3", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LLMRequestRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="The name of the task for tracking",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("prompt", models.TextField()),
                ("response", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "task",
                    models.CharField(
                        choices=[
                            ("chat_completion", "Chat Completion"),
                            ("completion", "Completion"),
                            ("create_embedding", "Create Embedding"),
                        ],
                        default="completion",
                        max_length=100,
                    ),
                ),
                ("completed_in_seconds", models.FloatField()),
                ("success", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
