# Generated by Django 4.2.8 on 2024-03-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0001_init"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMConfigRecords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("model_size", models.CharField(max_length=100)),
                ("model_family", models.CharField(max_length=100)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("hf", "HuggingFace"),
                            ("api", "API"),
                            ("llama.cpp", "llama.cpp"),
                        ],
                        default="hf",
                        max_length=100,
                    ),
                ),
                ("repo", models.CharField(blank=True, max_length=100, null=True)),
                ("filename", models.CharField(blank=True, max_length=100, null=True)),
                ("file_size", models.FloatField(blank=True, null=True)),
                ("available", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
