# Generated by Django 4.2.8 on 2024-07-04 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0001_init"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="llmconfigrecords",
            options={
                "verbose_name": "LLM Config Record",
                "verbose_name_plural": "LLM Config Records",
            },
        ),
        migrations.AlterModelOptions(
            name="llmrequestrecord",
            options={
                "verbose_name": "LLM Request Record",
                "verbose_name_plural": "LLM Request Records",
            },
        ),
        migrations.AlterModelOptions(
            name="llmrequestresultdownload",
            options={
                "verbose_name": "LLM Result Download",
                "verbose_name_plural": "LLM Result Downloads",
            },
        ),
    ]
