# Generated by Django 4.2.8 on 2024-03-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0002_add_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmrequestrecord",
            name="success",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="llmconfigrecords",
            name="model_type",
            field=models.CharField(
                choices=[
                    ("hf", "HuggingFace"),
                    ("api", "API"),
                    ("llama.cpp", "llama.cpp"),
                    ("chatglm.cpp", "chatglm.cpp"),
                ],
                default="hf",
                max_length=100,
            ),
        ),
    ]
