# Generated by Django 4.2.8 on 2024-03-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0004_change_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmrequestrecord",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="The name of the task for tracking",
                max_length=100,
                null=True,
            ),
        ),
    ]
