site_name: OpenOmni Framework by AI4WA
site_url: https://openbenang.ai4wa.com
theme:
  name: material
  logo: images/AI4WA.png
  favicon: images/favicon.ico
  features:
    - search.suggest
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/AI4WA/OpenBenang
nav:
  - Home: index.md
  - Leaderboard: LeaderBoard.md
  - Modules:
      - Client:
          - Introduction: Client/main.md
          - Setup: Client/setup.md
      - API: API.md
      - AI: AI.md
  - Source:
      - Client:
          - Introduction: Source/index.md
          - Listener:
              - Audio: Sources/Client/Listener/audios_acquire.md
              - Video: Sources/Client/Listener/videos_acquire.md
              - API: Sources/Client/Listener/api.md
              - Sync to Disk: Sources/Client/Listener/sync_files.md
              - Sync to S3: Sources/Client/Listener/sync_to_s3.md
              - Utils: Sources/Client/Listener/utils.md
              - Constants: Sources/Client/Listener/constants.md
          - Responder:
              - PlaySpeech: Sources/Client/Responder/play_speech.md
              - API: Sources/Client/Responder/api.md
              - Utils: Sources/Client/Responder/utils.md
              - Constants: Sources/Client/Responder/constants.md
      - AI: Sources/AI/main.md
plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true
            show_source_link: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AI4WA/OpenBenang
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ai4wa
  analytics:
    provider: google
    property: G-EPMRFY21NQ