site_name: OpenBenang by AI4WA
site_url: https://openbenang.ai4wa.com
theme:
  name: material
  logo: images/AI4WA.png
  favicon: images/favicon.ico
  features:
    - search.suggest
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/AI4WA/OpenBenang
plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true
            show_source_link: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AI4WA/OpenBenang
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ai4wa
  analytics:
    provider: google
    property: G-EPMRFY21NQ