site_name: OpenOmni Framework by AI4WA
site_url: https://openbenang.ai4wa.com
theme:
  name: material
  logo: images/AI4WA.png
  favicon: images/favicon.ico
  features:
    - search.suggest
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/AI4WA/OpenBenang
nav:
  - Home: index.md
  - Tutorial:
      - Table of Content: Tutorial/index.md
      - Fullstack Setup: Tutorial/setup.md
      - Benchmark and Annotation: Tutorial/benchmark_and_annotation.md
      - Customize Pipeline: Tutorial/pipeline_customisation.md
      - Customize Annotation: Tutorial/annotation_customisation.md
  - Deployment:
      - Table of Content: Deployment/index.md
      - Trial on Cloud: Deployment/trial-on-cloud.md
      - All in One Local Machine: Deployment/all-in-one-local-machine.md
      - Private Offline Deployment: Deployment/private-offline-deployment.md
      - Your Cloud: Deployment/your-cloud.md
  - Modules:
      - Client:
          - Introduction: Client/main.md
          - Setup: Client/setup.md
      - API: API/main.md
      - AI: AI.md

  - Source:
      - Client:
          - Introduction: Source/index.md
          - Listener:
              - Audio: Sources/Client/Listener/audios_acquire.md
              - Video: Sources/Client/Listener/videos_acquire.md
              - API: Sources/Client/Listener/api.md
              - Sync to Disk: Sources/Client/Listener/sync_files.md
              - Sync to S3: Sources/Client/Listener/sync_to_s3.md
              - Utils: Sources/Client/Listener/utils.md
              - Constants: Sources/Client/Listener/constants.md
          - Responder:
              - PlaySpeech: Sources/Client/Responder/play_speech.md
              - API: Sources/Client/Responder/api.md
              - Utils: Sources/Client/Responder/utils.md
              - Constants: Sources/Client/Responder/constants.md
      - AI: Sources/AI/main.md
plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true
            show_source_link: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AI4WA/OpenBenang
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ai4wa
  analytics:
    provider: google
    property: G-EPMRFY21NQ