# Generated by Django 4.2.8 on 2024-03-02 04:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0001_init"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="APIKey",
            new_name="OrgUserAPIKey",
        ),
    ]
