# Generated by Django 4.2.8 on 2024-03-02 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0002_add_api"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orguserapikey",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
