# Generated by Django 4.2.8 on 2024-03-02 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0003_add_api"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrgUserAPIKey",
        ),
    ]
