# Generated by Django 4.2.8 on 2024-03-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worker", "0001_add_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="work_type",
            field=models.CharField(
                choices=[("llm", "LLM"), ("stt", "Speech2Text"), ("gpu", "GPU")],
                help_text="Select the type of work",
                max_length=100,
            ),
        ),
    ]
