# Generated by Django 4.2.8 on 2024-04-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worker", "0003_add_gpu_worker"),
    ]

    operations = [
        migrations.AddField(
            model_name="gpuworker",
            name="task_type",
            field=models.CharField(
                choices=[("cpu", "CPU"), ("stt", "Speech2Text"), ("gpu", "GPU")],
                default="gpu",
                help_text="Select the type of work, it can be either CPU, GPU (both for LLM) or STT",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="work_type",
            field=models.CharField(
                choices=[
                    ("llm", "LLM"),
                    ("stt", "Speech2Text"),
                    ("gpu", "GPU"),
                    ("cpu", "CPU"),
                ],
                help_text="Select the type of work, GPU and CPU are for LLM, STT is for Speech2Text, llm is Legacy",
                max_length=100,
            ),
        ),
    ]
