# Generated by Django 4.2.8 on 2024-04-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0006_add_cmc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="work_type",
            field=models.CharField(
                choices=[
                    ("llm", "LLM"),
                    ("stt", "Speech2Text"),
                    ("tts", "Text2Speech"),
                    ("gpu", "GPU"),
                    ("cpu", "CPU"),
                    ("cmc", "Call Management Command"),
                ],
                help_text="Select the type of work, GPU and CPU are for LLM, STT is for Speech2Text, llm is Legacy",
                max_length=100,
            ),
        ),
    ]
