# Generated by Django 4.2.8 on 2024-07-07 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0001_init"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContextRAG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The emotion result of the text",
                        null=True,
                    ),
                ),
                (
                    "logs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The logs of the emotion detection",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The created time of the emotion detection",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The updated time of the emotion detection",
                    ),
                ),
                (
                    "annotations",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The annotations of the emotion detection",
                        null=True,
                    ),
                ),
                (
                    "multi_modal_conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rag",
                        to="hardware.datamultimodalconversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "RAG Result",
                "verbose_name_plural": "RAG Results",
            },
        ),
    ]
