# Generated by Django 4.2.8 on 2024-03-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0002_add_seconds"),
    ]

    operations = [
        migrations.CreateModel(
            name="HardWareDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(
                        help_text="The mac address of the hardware device",
                        max_length=100,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="The name of the hardware device",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        help_text="The type of the hardware device",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="The description of the hardware device",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The created time of the hardware device",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The updated time of the hardware device",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="audiodata",
            name="hardware_device_mac_address",
            field=models.CharField(
                blank=True,
                help_text="The mac address of the hardware device",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="videodata",
            name="hardware_device_mac_address",
            field=models.CharField(
                blank=True,
                help_text="The mac address of the hardware device",
                max_length=100,
                null=True,
            ),
        ),
    ]
