# Generated by Django 4.2.8 on 2024-03-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hardware", "0003_add_device"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hardwaredevice",
            name="mac_address",
            field=models.CharField(
                help_text="The mac address of the hardware device",
                max_length=100,
                unique=True,
            ),
        ),
    ]
