# Generated by Django 4.2.8 on 2024-07-03 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0003_add_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContextEmotionDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The emotion result of the text",
                        null=True,
                    ),
                ),
                (
                    "logs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The logs of the emotion detection",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The created time of the emotion detection",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The updated time of the emotion detection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataMultiModalConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The created time of the multi-modal conversation",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The updated time of the multi-modal conversation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResSpeech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text2speech_file",
                    models.CharField(
                        blank=True,
                        help_text="The audio file",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "played",
                    models.BooleanField(
                        default=False, help_text="The audio file is played or not"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The created time of the audio"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="The updated time of the audio"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(help_text="The text of the audio")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The created time of the llm response",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="The updated time of the llm response"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="llmresponse",
            name="data_text",
        ),
        migrations.RemoveField(
            model_name="llmresponse",
            name="home",
        ),
        migrations.RemoveField(
            model_name="text2speech",
            name="home",
        ),
        migrations.RemoveField(
            model_name="datatext",
            name="home",
        ),
        migrations.RemoveField(
            model_name="datatext",
            name="pipeline_triggered",
        ),
        migrations.AlterField(
            model_name="dataaudio",
            name="uid",
            field=models.CharField(
                help_text="the uid of the audio acquire session, can be treated as scenario id",
                max_length=100,
            ),
        ),
        migrations.DeleteModel(
            name="EmotionDetection",
        ),
        migrations.DeleteModel(
            name="LLMResponse",
        ),
        migrations.DeleteModel(
            name="Text2Speech",
        ),
        migrations.AddField(
            model_name="datamultimodalconversation",
            name="audio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="multi_modal_conversation",
                to="hardware.dataaudio",
            ),
        ),
        migrations.AddField(
            model_name="datamultimodalconversation",
            name="res_speech",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="multi_modal_conversation",
                to="hardware.resspeech",
            ),
        ),
        migrations.AddField(
            model_name="datamultimodalconversation",
            name="res_text",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="multi_modal_conversation",
                to="hardware.restext",
            ),
        ),
        migrations.AddField(
            model_name="datamultimodalconversation",
            name="text",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="multi_modal_conversation",
                to="hardware.datatext",
            ),
        ),
        migrations.AddField(
            model_name="datamultimodalconversation",
            name="video",
            field=models.ManyToManyField(
                blank=True,
                related_name="multi_modal_conversation",
                to="hardware.datavideo",
            ),
        ),
        migrations.AddField(
            model_name="contextemotiondetection",
            name="multi_modal_conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emotion_detection",
                to="hardware.datamultimodalconversation",
            ),
        ),
    ]
