# Generated by Django 4.2.8 on 2024-03-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0004_add_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="Text2Speech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hardware_device_mac_address",
                    models.CharField(
                        blank=True,
                        help_text="The mac address of the hardware device",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, help_text="The text of the audio", null=True
                    ),
                ),
                (
                    "audio_file",
                    models.CharField(
                        blank=True,
                        help_text="The audio file",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "spoken",
                    models.BooleanField(
                        default=False, help_text="The audio file is spoken or not"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The created time of the audio"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="The updated time of the audio"
                    ),
                ),
            ],
            options={
                "db_table": "text2speech",
            },
        ),
    ]
