# Generated by Django 4.2.8 on 2024-07-03 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0004_update_data_structure"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contextemotiondetection",
            options={
                "verbose_name": "Context Emotion",
                "verbose_name_plural": "Context Emotions",
            },
        ),
        migrations.AlterModelOptions(
            name="dataaudio",
            options={
                "verbose_name": "Data Audio",
                "verbose_name_plural": "Data Audios",
            },
        ),
        migrations.AlterModelOptions(
            name="datamultimodalconversation",
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
            },
        ),
        migrations.AlterModelOptions(
            name="datatext",
            options={"verbose_name": "Data Text", "verbose_name_plural": "Data Texts"},
        ),
        migrations.AlterModelOptions(
            name="datavideo",
            options={
                "verbose_name": "Data Video",
                "verbose_name_plural": "Data Videos",
            },
        ),
        migrations.AlterModelOptions(
            name="hardwaredevice",
            options={
                "verbose_name": "Hardware Device",
                "verbose_name_plural": "Hardware Devices",
            },
        ),
        migrations.AlterModelOptions(
            name="resspeech",
            options={
                "verbose_name": "Res Speech",
                "verbose_name_plural": "Res Speeches",
            },
        ),
        migrations.AlterModelOptions(
            name="restext",
            options={"verbose_name": "Res Text", "verbose_name_plural": "Res Texts"},
        ),
        migrations.AlterField(
            model_name="datamultimodalconversation",
            name="audio",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="multi_modal_conversation",
                to="hardware.dataaudio",
            ),
        ),
        migrations.AlterField(
            model_name="datamultimodalconversation",
            name="res_speech",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="multi_modal_conversation",
                to="hardware.resspeech",
            ),
        ),
        migrations.AlterField(
            model_name="datamultimodalconversation",
            name="res_text",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="multi_modal_conversation",
                to="hardware.restext",
            ),
        ),
        migrations.AlterField(
            model_name="datamultimodalconversation",
            name="text",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="multi_modal_conversation",
                to="hardware.datatext",
            ),
        ),
    ]
