# Generated by Django 4.2.8 on 2024-03-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0005_add_text2speech"),
    ]

    operations = [
        migrations.AddField(
            model_name="videodata",
            name="video_record_minute",
            field=models.DateTimeField(
                blank=True, help_text="The minute of the video", null=True
            ),
        ),
    ]
