# Generated by Django 4.2.8 on 2024-07-03 07:19

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0005_update_rel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datavideo",
            name="video_record_minute",
        ),
        migrations.AddField(
            model_name="datavideo",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 3, 15, 19, 43, 623413),
                help_text="The end time of the video",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="datavideo",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 3, 15, 19, 50, 34168),
                help_text="The start time of the video",
            ),
            preserve_default=False,
        ),
    ]
