# Generated by Django 4.2.8 on 2024-03-19 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hardware", "0006_add_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReactionToAudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "react_already",
                    models.BooleanField(
                        default=False,
                        help_text="The audio data has been reacted or not",
                    ),
                ),
                (
                    "emotion_result",
                    models.JSONField(
                        blank=True,
                        help_text="The emotion result of the audio",
                        null=True,
                    ),
                ),
                (
                    "failed",
                    models.BooleanField(
                        default=False, help_text="The reaction failed or not"
                    ),
                ),
                (
                    "failed_reason",
                    models.TextField(
                        blank=True,
                        help_text="The reason of the reaction failed",
                        null=True,
                    ),
                ),
                (
                    "llm_response",
                    models.JSONField(
                        blank=True, help_text="The llm response of the audio", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The created time of the reaction"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="The updated time of the reaction"
                    ),
                ),
                (
                    "audio",
                    models.OneToOneField(
                        blank=True,
                        help_text="The audio data",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reaction",
                        to="hardware.audiodata",
                    ),
                ),
            ],
        ),
    ]
