# Generated by Django 4.2.8 on 2024-07-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0006_add_new_start_end_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="datamultimodalconversation",
            name="track_id",
            field=models.CharField(
                blank=True,
                help_text="The track id of the multimodal conversation",
                max_length=100,
                null=True,
            ),
        ),
    ]
