# Generated by Django 4.2.8 on 2024-04-11 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hardware", "0008_refactor_hardware"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dataaudio",
            name="translation_in_seconds",
        ),
    ]
