# Generated by Django 4.2.8 on 2024-04-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hardware", "0009_remove_translation_second"),
    ]

    operations = [
        migrations.AddField(
            model_name="datatext",
            name="translation_in_seconds",
            field=models.FloatField(
                blank=True, help_text="The time taken to translate the audio", null=True
            ),
        ),
    ]
