# Generated by Django 4.2.8 on 2024-04-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hardware", "0010_add_to_data_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="datatext",
            name="logs",
            field=models.JSONField(
                blank=True, default=dict, help_text="The logs of the text", null=True
            ),
        ),
    ]
