# Generated by Django 4.2.8 on 2024-07-05 06:48

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("hardware", "0010_add_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datamultimodalconversation",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
