# Generated by Django 4.2.8 on 2024-04-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hardware", "0011_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="datatext",
            name="pipeline_triggered",
            field=models.BooleanField(
                default=False, help_text="The pipeline is triggered or not"
            ),
        ),
    ]
