# Generated by Django 4.2.8 on 2024-04-11 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hardware", "0012_add_pipeline_trigger"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="text2speech",
            name="hardware_device_mac_address",
        ),
    ]
