services:
  ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: AIContainer
    command: /app/entrypoint.sh
    volumes:
      - .:/app
    environment:
      - TOKEN={YOUR_TOKEN}
    network_mode: host
