services:
  db:
    image: postgres:13
    container_name: DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: API
    command: /usr/src/app/entrypoint.sh
    volumes:
      - .:/usr/src/app
      - .aws:/root/.aws
      - ../Client/Listener/data:/usr/src/client/Listener/data
      - ../AI/data/tts:/usr/src/client/Responder/data
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=yourdbname
      - DB_USER=youruser
      - DB_PASS=yourpassword
      - DB_SERVICE=DB
      - DB_PORT=5432
    depends_on:
      - db

  hasura:
    image: hasura/graphql-engine:v2.38.0.cli-migrations-v3
    container_name: HASURA
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./hasura/:/Javr5/
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://youruser:yourpassword@DB:5432/yourdbname
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: yn
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "public"
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256", "key": "django-insecure-yk8_z-l5)!2p2ii*^)i&4z)#j94d#f3by&j1*g*ru=)q7m#jw6"}' # Replace with environment variable JWT secret
    depends_on:
      - db


volumes:
  postgres_data:
  whisper_cache:
