name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy_cmwhver:
    name: Deploy to Paswey
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: "146.118.70.154"
          username: pascal
          password: ${{ secrets.PASWEY_PASSWORD }}
          port: 22
          source: "assistant.tar"
          target: "/home/pascal/"

      - name: Restart server
        uses: appleboy/ssh-action@master
        with:
          host: "146.118.70.154"
          username: pascal
          password: ${{ secrets.PASWEY_PASSWORD }}
          port: 22
          script: cd /home/pascal && rm -rf Assistant && mkdir -p Assistant && tar xopf assistant.tar -C Assistant && cd Assistant && docker-compose up -d