version: '3.8'
services:
  web:
    container_name: web
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
    volumes:
      - .:/usr/src/app
